export const DASHBOARD_TITLE =
  "AI for Healthcare Compliance and Regulations Across Countries";

export const DASHBOARD_TAGLINE =
  "Interactive comparison of AI regulations in healthcare across 20 countries and 6 regions";

export type GuideSection = {
  id: string;
  title: string;
  body: string[];
};

export const METHOD_SECTIONS: GuideSection[] = [
  {
    id: "score",
    title: "What is the compliance score? How is it calculated?",
    body: [
      "Each country is scored on seven regulatory themes on a 1–10 scale. A score of 1 means little or no documented requirement for that theme; 10 means a mature, enforceable framework with clear guidance and operational practice.",
      "The overall compliance score shown in KPIs, the world map, and top-performer charts is the arithmetic mean of the theme scores currently selected in the slicers:",
      "Overall score = (sum of selected theme scores) ÷ (number of selected themes), rounded to one decimal place.",
      "Example: if Data Privacy = 8, Clinical Validation = 9, and Approval Process = 9, overall = (8 + 9 + 9) / 3 = 8.7. Changing the theme filters recalculates this average immediately. Use-case readiness (radiology, pathology, genomics, drug discovery) is a weighted mean of the same theme scores, using weights that reflect which themes matter most for that clinical application.",
    ],
  },
  {
    id: "pipeline",
    title: "Full pipeline: data collection to score calculation",
    body: [
      "1. Scope. Twenty jurisdictions were selected to cover North America, Europe, Asia, the Middle East, Africa, and Oceania, including both advanced regulators and emerging markets.",
      "2. Source collection (2018–2026). Primary sources were official regulatory texts and agency guidance (FDA, EMA, MHRA, NMPA, PMDA, TGA, Health Canada, WHO, OECD, IMDRF, national data-protection authorities). Secondary sources were peer-reviewed papers from PubMed, Scopus, IEEE Xplore, Google Scholar, and SSRN.",
      "3. Coding schema. Each country record was structured into the same fields: regulatory body, privacy law, AI-specific regulation, medical-device framework, approval process, data governance, clinical validation, transparency, ethics, post-market surveillance, liability, legislations, challenges, and notable developments.",
      "4. Theme scoring. For each of the seven themes, documentary evidence was mapped to a 1–10 ordinal score (presence of law or guidance, specificity to health AI / SaMD, enforcement or reporting mechanisms, and alignment with IMDRF / WHO / GMLP).",
      "5. Maturity label. A qualitative maturity class (Early → Advanced) was assigned from the same evidence: AI-specific rules, device pathway, approval volume, and privacy/ethics enforcement — not from a hidden formula on the scores alone.",
      "6. Dashboard derivation. The app loads the structured JSON, applies region/maturity/theme filters, then computes overall averages, gaps (max − min per theme), use-case readiness (weighted scores), and charts. No scores are generated by a machine-learning model at runtime.",
    ],
  },
  {
    id: "maturity",
    title: "Maturity distribution — how is it calculated?",
    body: [
      "Maturity is a country-level class stored in the dataset (maturity_level). The Maturity mix chart simply counts how many countries in the current filter fall into each class. It is a frequency distribution, not a new statistical model.",
      "Classes and how they were determined from the documentary review:",
      "Early — Limited AI-specific healthcare regulation, few or no documented AI device approvals, and basic or recently introduced data-protection rules (e.g. Nigeria, Kenya).",
      "Emerging — Data protection and/or voluntary AI ethics exist, but SaMD / AI-device pathways are still forming and approval volume is low (e.g. Saudi Arabia, South Africa).",
      "Developing — A medical-device framework is in place and AI guidance is appearing, with moderate institutional capacity (e.g. India, Brazil).",
      "Moderate — Functioning SaMD registration, international alignment (IMDRF-style risk classes), and a working post-market system, with mid-range approval volume (e.g. Australia).",
      "Advanced — Dedicated AI/ML SaMD pathways or high-risk AI law, substantial device authorizations, lifecycle governance (e.g. TPLC / PCCP), and enforceable privacy or ethics rules (e.g. United States, EU, United Kingdom, Germany, Japan, Singapore, South Korea, China, Canada, Israel, Switzerland).",
    ],
  },
  {
    id: "variables",
    title: "Meaning of Approval Process and every dashboard variable",
    body: [
      "Approval Process: how an AI health product reaches the market — risk class, submission type (510(k), De Novo, PMA, MDR conformity, NMPA registration, etc.), clinical evidence expected, and whether adaptive algorithms have a change-control path. Higher scores mean a published, operational SaMD/AI pathway rather than general device law only.",
      "Data Privacy: health-data protection law (HIPAA, GDPR, PIPL, LGPD, POPIA, etc.), special rules for sensitive/health data, DPIAs, and cross-border transfer limits.",
      "Clinical Validation: evidence expected before use — analytical validation, clinical validation, clinical utility, GMLP-style data quality, bias/subgroup analysis, and real-world evidence acceptance.",
      "Transparency: duties to document, log, explain, or disclose AI use (EU AI Act high-risk duties, GDPR Art. 22, China’s algorithm filing vs. voluntary FDA/NIST guidance).",
      "Ethics: national or WHO-aligned principles (autonomy, fairness, accountability) and whether they are voluntary or legally binding.",
      "Post-Market Surveillance: adverse-event reporting, performance monitoring after deployment, and lifecycle / total-product-lifecycle oversight for model drift.",
      "Liability: who is accountable if AI contributes to harm — product liability, malpractice, or AI-specific rules (e.g. proposed EU AI liability).",
      "Other dashboard fields: Region (geographic grouping); Maturity (class above); Regulatory body (lead agency); AI devices approved (published authorization counts where available); First AI regulation year (first dedicated AI/SaMD-relevant instrument); Privacy law / AI regulation / device framework (short labels); Country profile text (narrative coding of each theme).",
    ],
  },
  {
    id: "classes",
    title: "Profile: full definition of classes and how they are determined",
    body: [
      "Device risk classes (shown in the literature review, not as a separate slicer) follow each regulator’s published scheme, adapted from IMDRF SaMD risk categorization (significance of information × state of the healthcare condition):",
      "USA FDA: Class I (low), II (moderate, typically 510(k)), III (high, PMA).",
      "EU MDR: Class I, IIa, IIb, III — SaMD class depends on intended purpose and impact on clinical decisions.",
      "China NMPA: Class I, II, III. Canada and Japan: Class I–IV. Australia TGA: Class I, IIa, IIb, III.",
      "Dashboard maturity classes (Early, Emerging, Developing, Moderate, Advanced) are independent of device Class I–III. They describe the jurisdiction’s regulatory system, determined by qualitative coding of laws, guidance, enforcement capacity, and approval activity — then stored on each country record. Device Class I–III describes the product; maturity describes the country’s governance.",
    ],
  },
  {
    id: "gaps",
    title: "What do we mean by gaps?",
    body: [
      "A compliance gap is the difference between the highest and lowest country scores for one theme in the current filter: gap = max(score) − min(score). A large gap (e.g. Clinical Validation) means some jurisdictions have strong evidence rules while others have almost none. The Theme Analysis page names the leader and laggard for each theme. In the literature, “gaps” also means qualitative shortfalls: missing AI-specific law, weak enforcement, capacity limits in the Global South, or an ethics gap between principles and practice (Mittelstadt, 2019).",
    ],
  },
  {
    id: "convergence",
    title: "What do we mean by convergence trends?",
    body: [
      "Convergence trends are regulatory patterns that are spreading across many jurisdictions rather than remaining unique to one country. This dashboard uses the dataset’s global_trends list (adoption level High / Medium / Low and year emerged). Examples from the review: risk-based SaMD classification (IMDRF); GDPR-style comprehensive data protection; GMLP-style good machine-learning practice; lifecycle / adaptive-algorithm governance (FDA PCCP); and the shift from voluntary ethics principles toward binding rules (EU AI Act). Convergence does not mean identical laws — it means shared principles and similar instruments.",
    ],
  },
  {
    id: "recommendations",
    title: "Where did recommendations come from?",
    body: [
      "Dashboard “key takeaways” and the literature recommendations are a synthesis of primary instruments and peer-reviewed work, not a new Delphi survey. Principal sources: WHO Ethics and Governance of AI for Health (2021); IMDRF SaMD risk framework (2014); FDA AI/ML SaMD Action Plan (2021) and PCCP guidance (2023); FDA–Health Canada–MHRA Good Machine Learning Practice (2021); EU AI Act (Regulation (EU) 2024/1689); EU MDR 2017/745; GDPR; NIST AI RMF 1.0 (2023); OECD AI Policy Observatory; and papers including Topol (2019), Gerke et al. (2020), Muehlematter et al. (2021), Jobin et al. (2019), and Wu et al. (2021).",
      "The five recommendations on the review (harmonize via IMDRF/WHO; build capacity in developing countries; AI-specific evidence methods; operationalize ethics with standards; address liability before harm cases proliferate) follow section 10.3 of that synthesis.",
    ],
  },
];

export const LITERATURE_SECTIONS: { heading: string; paragraphs: string[] }[] = [
  {
    heading: "Abstract",
    paragraphs: [
      "Artificial Intelligence (AI) is transforming healthcare through diagnostics, clinical decision support, drug discovery, and patient management. Deployment in clinical settings is governed by a complex, rapidly evolving landscape of regulations, compliance frameworks, and ethical guidelines that vary across countries. This review synthesizes policy documents, regulatory guidelines, and peer-reviewed research across 20 countries in North America, Europe, Asia, the Middle East, Africa, and Oceania. Seven themes are mapped: data privacy and governance, clinical validation and safety, regulatory approval processes, algorithmic transparency, ethical considerations, post-market surveillance, and liability. Findings show a global trend toward risk-based regulation and comprehensive data protection, with large disparities in enforcement, AI-specific legislation, and ethical governance between advanced economies and emerging markets.",
    ],
  },
  {
    heading: "1. Introduction",
    paragraphs: [
      "AI-based Software as a Medical Device (SaMD) now assists clinicians in radiology, pathology, ophthalmology, cardiology, and genomics (Topol, 2019; Rajpurkar et al., 2022). The U.S. FDA has authorized hundreds of AI/ML-enabled devices, reflecting rapid growth (FDA, 2025). Unlike traditional devices, AI can be adaptive, opaque, and trained on biased data — raising questions existing frameworks were not designed to address (Gerke et al., 2020; Char et al., 2018).",
      "Objectives: (1) synthesize literature on AI healthcare regulation; (2) analyze key themes; (3) map regional similarities and differences; (4) highlight gaps, challenges, and trends; (5) inform this interactive dashboard. Methods used PubMed, Scopus, IEEE Xplore, Google Scholar, SSRN; FDA, EMA, MHRA, NMPA, WHO, OECD; national AI strategies and device rules; search terms on SaMD, ethics, health-data governance; inclusion 2018–2026; scope 20 countries / 6 regions.",
    ],
  },
  {
    heading: "2. Regulatory frameworks for AI medical devices",
    paragraphs: [
      "IMDRF (2014) categorizes SaMD by the significance of information and the healthcare condition. The United States uses 510(k), De Novo, and PMA plus the 2021 AI/ML SaMD Action Plan. The EU combines MDR 2017/745 with the high-risk layer of the AI Act (2024). Japan uses PMDA DASH for SaMD; China issued NMPA Guiding Principles for AI medical device registration (2021).",
      "Risk-based classification is near-universal (FDA I–III; MDR I–III; NMPA I–III; Canada/Japan I–IV; TGA I–III). Adaptive algorithms are addressed by FDA Predetermined Change Control Plans (2023) and EU AI Act ongoing conformity (Babic et al., 2019; Muehlematter et al., 2021).",
    ],
  },
  {
    heading: "3–8. Privacy, validation, transparency, ethics, surveillance, liability",
    paragraphs: [
      "GDPR (2018) set a global benchmark (including Art. 22 on automated decisions). Parallel laws include Brazil LGPD, India DPDP, China PIPL, South Africa POPIA, Nigeria NDPA, Kenya DPA, Thailand PDPA, Saudi PDPL, UAE Decree 45, Switzerland nFADP. Health-specific overlays include HIPAA (USA), EHDS (EU), and Australia’s My Health Records Act.",
      "Clinical validation follows analytical validation, clinical validation, and clinical utility. FDA, Health Canada, and MHRA published GMLP (2021). Bias literature includes dermatology and chest X-ray disparities and the Obermeyer et al. (2019) risk-algorithm study.",
      "Transparency ranges from mandated (EU AI Act, China algorithm rules, GDPR) to voluntary (FDA, NIST AI RMF, Singapore Model Framework). WHO (2021) set six ethics principles; Jobin et al. (2019) mapped a global explosion of guidelines. Lifecycle surveillance (FDA TPLC, MDR incident reporting) and unresolved liability (product vs malpractice vs proposed EU AI liability) close the theme set.",
    ],
  },
  {
    heading: "9. Comparative regional analysis",
    paragraphs: [
      "North America: innovation-friendly, high approval volume, GMLP leadership; US lacks a comprehensive federal AI law. Europe: rights-based EU AI Act + MDR + GDPR; implementation and notified-body capacity are constraints. East Asia: rapid government-driven rules, sandboxes, data-localization tensions. South/Southeast Asia: Singapore as governance leader; India and Thailand building capacity. Middle East: ambitious strategies; Israel’s health-data infrastructure. Africa: data-protection laws ahead of AI-device rules; severe capacity and infrastructure gaps.",
    ],
  },
  {
    heading: "10–11. Convergence, recommendations, conclusion",
    paragraphs: [
      "Convergence: risk-based SaMD classes; GDPR-style privacy laws; IMDRF/WHO/GMLP harmonization; ethics moving from voluntary to binding. Emerging challenges: generative/foundation models, continuous learning, a Global South regulatory divide, and data-localization fragmentation.",
      "Recommendations (from WHO, IMDRF, GMLP, EU AI Act, FDA SaMD Action Plan, and the cited literature): strengthen international harmonization; build regulatory capacity in developing countries; develop AI-specific evidence methods; operationalize ethics with technical standards; address liability before harm cases proliferate. The landscape is rapidly evolving, with converging principles and persistent diversity in maturity and enforcement.",
    ],
  },
];

export const SOURCE_LINKS: { title: string; url: string; note: string }[] = [
  {
    title: "FDA AI/ML-Based SaMD Action Plan (2021)",
    url: "https://www.fda.gov/media/145022/download",
    note: "Primary US AI medical-device policy",
  },
  {
    title: "FDA — Artificial Intelligence in SaMD",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-software-medical-device",
    note: "Agency overview and device listings",
  },
  {
    title: "EU AI Act — Regulation (EU) 2024/1689",
    url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    note: "Binding high-risk AI rules including health",
  },
  {
    title: "EU MDR — Regulation (EU) 2017/745",
    url: "https://eur-lex.europa.eu/eli/reg/2017/745/oj/eng",
    note: "Medical device / SaMD classification",
  },
  {
    title: "GDPR — Regulation (EU) 2016/679",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679",
    note: "Health data and automated decisions",
  },
  {
    title: "WHO — Ethics and Governance of AI for Health (2021)",
    url: "https://www.who.int/publications/i/item/9789240029200",
    note: "Six global ethics principles",
  },
  {
    title: "OECD.AI Policy Observatory",
    url: "https://oecd.ai/en/",
    note: "Comparative national AI policy",
  },
  {
    title: "IMDRF SaMD risk categorization (2014)",
    url: "https://www.imdrf.org/docs/imdrf/final/technical/imdrf-tech-140918-samd-framework-risk-categorization-141013.pdf",
    note: "International SaMD risk classes",
  },
  {
    title: "GMLP — FDA, Health Canada, MHRA (2021)",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/good-machine-learning-practice-medical-device-development-guiding-principles",
    note: "Ten good ML practice principles",
  },
  {
    title: "NIST AI Risk Management Framework 1.0 (2023)",
    url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10",
    note: "Voluntary US AI governance",
  },
  {
    title: "PubMed",
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    note: "Peer-reviewed literature search",
  },
  {
    title: "European Medicines Agency",
    url: "https://www.ema.europa.eu/",
    note: "EU medicines and device-adjacent guidance",
  },
];

/** Topic-tagged references for jury presentation on the Literature page */
export type TopicReference = {
  id: string;
  title: string;
  authors: string;
  year: number;
  type: string;
  topic: string;
  url?: string;
  why: string;
};

export const REFERENCE_TOPICS = [
  "All",
  "Regulation / SaMD",
  "Data privacy",
  "Clinical validation",
  "Ethics",
  "Transparency",
  "Liability",
  "Post-market",
] as const;

export const TOPIC_REFERENCES: TopicReference[] = [
  {
    id: "who2021",
    title: "Ethics and Governance of Artificial Intelligence for Health",
    authors: "World Health Organization",
    year: 2021,
    type: "Guideline",
    topic: "Ethics",
    url: "https://www.who.int/publications/i/item/9789240029200",
    why: "Global ethics principles used for comparative scoring of ethical frameworks.",
  },
  {
    id: "fda2021",
    title: "AI/ML-Based Software as a Medical Device (SaMD) Action Plan",
    authors: "U.S. FDA",
    year: 2021,
    type: "Regulatory Document",
    topic: "Regulation / SaMD",
    url: "https://www.fda.gov/media/145022/download",
    why: "Core US pathway for AI medical devices; informs approval-process scores.",
  },
  {
    id: "fda2023",
    title: "Predetermined Change Control Plan (PCCP) for AI/ML Device Software",
    authors: "U.S. FDA",
    year: 2023,
    type: "Regulatory Document",
    topic: "Post-market",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-software-medical-device",
    why: "Lifecycle / adaptive-algorithm governance (TPLC thinking).",
  },
  {
    id: "euaiact",
    title: "Regulation (EU) 2024/1689 — Artificial Intelligence Act",
    authors: "European Parliament and Council",
    year: 2024,
    type: "Legislation",
    topic: "Regulation / SaMD",
    url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    why: "Binding high-risk AI rules; raises EU transparency and ethics scores.",
  },
  {
    id: "mdr",
    title: "EU Medical Device Regulation (MDR) 2017/745",
    authors: "European Parliament and Council",
    year: 2017,
    type: "Legislation",
    topic: "Regulation / SaMD",
    url: "https://eur-lex.europa.eu/eli/reg/2017/745/oj/eng",
    why: "SaMD risk classification and conformity assessment in Europe.",
  },
  {
    id: "gdpr",
    title: "General Data Protection Regulation (GDPR) 2016/679",
    authors: "European Parliament and Council",
    year: 2016,
    type: "Legislation",
    topic: "Data privacy",
    url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679",
    why: "Benchmark for health-data protection and automated decision-making (Art. 22).",
  },
  {
    id: "imdrf",
    title: "Software as a Medical Device: Risk Categorization Framework",
    authors: "IMDRF",
    year: 2014,
    type: "Framework",
    topic: "Regulation / SaMD",
    url: "https://www.imdrf.org/docs/imdrf/final/technical/imdrf-tech-140918-samd-framework-risk-categorization-141013.pdf",
    why: "International foundation for risk-based SaMD classification.",
  },
  {
    id: "gmlp",
    title: "Good Machine Learning Practice for Medical Device Development",
    authors: "FDA, Health Canada, MHRA",
    year: 2021,
    type: "Guiding Principles",
    topic: "Clinical validation",
    url: "https://www.fda.gov/medical-devices/software-medical-device-samd/good-machine-learning-practice-medical-device-development-guiding-principles",
    why: "Harmonized good ML practice used in validation-theme scoring.",
  },
  {
    id: "nist",
    title: "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
    authors: "NIST",
    year: 2023,
    type: "Framework",
    topic: "Ethics",
    url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-ai-rmf-10",
    why: "US voluntary AI risk governance referenced for ethics/transparency.",
  },
  {
    id: "oecd",
    title: "OECD.AI Policy Observatory",
    authors: "OECD",
    year: 2024,
    type: "Policy",
    topic: "Regulation / SaMD",
    url: "https://oecd.ai/en/",
    why: "Comparative national AI policy context across regions.",
  },
  {
    id: "topol2019",
    title: "High-Performance Medicine: The Convergence of Human and Artificial Intelligence",
    authors: "Topol, E. J.",
    year: 2019,
    type: "Research",
    topic: "Clinical validation",
    url: "https://pubmed.ncbi.nlm.nih.gov/30617339/",
    why: "Foundational clinical AI overview cited in the literature review.",
  },
  {
    id: "rajpurkar2022",
    title: "AI in Health and Medicine",
    authors: "Rajpurkar, P., Chen, E., Banerjee, O., & Topol, E. J.",
    year: 2022,
    type: "Research",
    topic: "Clinical validation",
    url: "https://pubmed.ncbi.nlm.nih.gov/35058619/",
    why: "Clinical AI applications (imaging, etc.) motivating regulatory comparison.",
  },
  {
    id: "gerke2020",
    title: "Ethical and Legal Challenges of Artificial Intelligence-Driven Healthcare",
    authors: "Gerke, S., Minssen, T., & Cohen, I. G.",
    year: 2020,
    type: "Research",
    topic: "Ethics",
    why: "Legal/ethical challenges framing the seven compliance themes.",
  },
  {
    id: "muehlematter2021",
    title: "Approval of AI/ML Medical Devices in the USA and Europe (2015–20)",
    authors: "Muehlematter, U. J., Daniore, P., & Vokinger, K. N.",
    year: 2021,
    type: "Research",
    topic: "Regulation / SaMD",
    url: "https://pubmed.ncbi.nlm.nih.gov/33357500/",
    why: "Comparative approval evidence for US vs Europe.",
  },
  {
    id: "wu2021",
    title: "How Medical AI Devices Are Evaluated: Limitations and Recommendations from FDA Approvals",
    authors: "Wu, E., Wu, K., Daneshjou, R., et al.",
    year: 2021,
    type: "Research",
    topic: "Clinical validation",
    url: "https://pubmed.ncbi.nlm.nih.gov/33820998/",
    why: "Shows validation gaps in cleared AI devices.",
  },
  {
    id: "obermeyer2019",
    title: "Dissecting Racial Bias in an Algorithm Used to Manage the Health of Populations",
    authors: "Obermeyer, Z., Powers, B., Vogeli, C., & Mullainathan, S.",
    year: 2019,
    type: "Research",
    topic: "Ethics",
    url: "https://pubmed.ncbi.nlm.nih.gov/31649194/",
    why: "Landmark bias study supporting fairness/ethics theme.",
  },
  {
    id: "jobin2019",
    title: "The Global Landscape of AI Ethics Guidelines",
    authors: "Jobin, A., Ienca, M., & Vayena, E.",
    year: 2019,
    type: "Research",
    topic: "Ethics",
    url: "https://www.nature.com/articles/s42256-019-0088-2",
    why: "Maps proliferation of AI ethics guidelines worldwide.",
  },
  {
    id: "babic2019",
    title: "Algorithms on Regulatory Lockdown in Medicine",
    authors: "Babic, B., Gerke, S., Evgeniou, T., & Cohen, I. G.",
    year: 2019,
    type: "Research",
    topic: "Post-market",
    url: "https://pubmed.ncbi.nlm.nih.gov/31831634/",
    why: "Adaptive algorithms and lifecycle regulation argument.",
  },
  {
    id: "hwang2019",
    title: "Lifecycle Regulation of AI- and ML-Based Software Devices in Medicine",
    authors: "Hwang, T. J., Kesselheim, A. S., & Vokinger, K. N.",
    year: 2019,
    type: "Research",
    topic: "Post-market",
    url: "https://pubmed.ncbi.nlm.nih.gov/31697338/",
    why: "Supports Total Product Lifecycle surveillance theme.",
  },
  {
    id: "price2019",
    title: "Potential Liability for Physicians Using Artificial Intelligence",
    authors: "Price, W. N., Gerke, S., & Cohen, I. G.",
    year: 2019,
    type: "Research",
    topic: "Liability",
    url: "https://pubmed.ncbi.nlm.nih.gov/31584624/",
    why: "Physician/product liability issues for clinical AI.",
  },
  {
    id: "ghassemi2021",
    title: "The False Hope of Current Approaches to Explainable AI in Health Care",
    authors: "Ghassemi, M., Oakden-Rayner, L., & Beam, A. L.",
    year: 2021,
    type: "Research",
    topic: "Transparency",
    url: "https://pubmed.ncbi.nlm.nih.gov/34731977/",
    why: "Critical view of explainability used in transparency theme.",
  },
  {
    id: "rudin2019",
    title: "Stop Explaining Black Box ML Models for High Stakes Decisions…",
    authors: "Rudin, C.",
    year: 2019,
    type: "Research",
    topic: "Transparency",
    url: "https://www.nature.com/articles/s42256-019-0048-x",
    why: "Interpretable vs post-hoc XAI debate for clinical AI.",
  },
  {
    id: "char2018",
    title: "Implementing Machine Learning in Health Care — Addressing Ethical Challenges",
    authors: "Char, D. S., Shah, N. H., & Magnus, D.",
    year: 2018,
    type: "Research",
    topic: "Ethics",
    url: "https://pubmed.ncbi.nlm.nih.gov/29539284/",
    why: "Early NEJM framing of ML ethics in care delivery.",
  },
  {
    id: "cohen2018",
    title: "HIPAA and Protecting Health Information in the 21st Century",
    authors: "Cohen, I. G., & Mello, M. M.",
    year: 2018,
    type: "Research",
    topic: "Data privacy",
    url: "https://pubmed.ncbi.nlm.nih.gov/29800120/",
    why: "US health privacy baseline vs GDPR-style laws.",
  },
  {
    id: "mittelstadt2019",
    title: "Principles Alone Cannot Guarantee Ethical AI",
    authors: "Mittelstadt, B.",
    year: 2019,
    type: "Research",
    topic: "Ethics",
    url: "https://www.nature.com/articles/s42256-019-0114-4",
    why: "Ethics gap between principles and enforceable practice.",
  },
  {
    id: "petersen2022",
    title: "Recommendations for Safe, Effective Use of Adaptive CDS in the US",
    authors: "Petersen, C., et al.",
    year: 2022,
    type: "Research",
    topic: "Post-market",
    url: "https://pubmed.ncbi.nlm.nih.gov/35024858/",
    why: "Adaptive clinical decision support and monitoring.",
  },
  {
    id: "seyed2021",
    title: "Underdiagnosis Bias of AI Algorithms Applied to Chest Radiographs",
    authors: "Seyyed-Kalantari, L., et al.",
    year: 2021,
    type: "Research",
    topic: "Clinical validation",
    url: "https://pubmed.ncbi.nlm.nih.gov/34750592/",
    why: "Subgroup performance / bias evidence for validation theme.",
  },
  {
    id: "goodman2017",
    title: "EU Regulations on Algorithmic Decision-Making and a Right to Explanation",
    authors: "Goodman, B., & Flaxman, S.",
    year: 2017,
    type: "Research",
    topic: "Transparency",
    url: "https://ojs.aaai.org/aimagazine/index.php/aimagazine/article/view/2740",
    why: "GDPR Art. 22 transparency implications for clinical AI.",
  },
];
